name: Time app

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'app_python/**'
  push:
    branches:
      - lab3
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'app_python/**'

jobs:
  build-lint-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Python set up
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app_python/requirements.txt
      
      - name: Lint Code (flake8)
        run: |
          pip install flake8
          flake8 main.py ut/

      - name: Run Unit Tests
        run: |
          python -m unittest discover ut

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t my-docker-app:latest .

            - name: Push Docker Image
        run: |
          docker tag my-docker-app:latest ${{ secrets.DOCKER_USERNAME }}/devops-labs:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-labs:latest